### ISSUE TITLE
Healthy Beginnings At Home Should Not Receive Paper Bill

### ISSUE THREAD

**Issue by entomacy** [COHHIO/hmis.billing#14] opened 2023-08-21 13:24 UTC
HBAH received a bill for 2023Q2. We should maybe write their agency ID out of the billing code that generates paper invoices.

**Comment by trevinflick** [comment] 2023-08-21 13:50
This looks like a duplicate of #13

**Comment by trevinflick** [comment] 2023-11-28 17:54
Temporarily taking out HBAH so they don't appear in the paper billing statement

80dacc5

**Closed by trevinflick** 2023-11-28 17:54 UTC
